-- All are Hibernate Queries
-- Generated based on the entities defined in the project

create table app_user
(
    created_at timestamp(6),
    id         bigint generated by default as identity,
    updated_at timestamp(6),
    email      varchar(255) not null unique,
    name       varchar(255) not null,
    password   varchar(255) not null,
    primary key (id)
)

create table booking
(
    rooms_count         integer      not null,
    check_in_date_time  timestamp(6) not null,
    check_out_date_time timestamp(6) not null,
    created_at          timestamp(6),
    hotel_id            bigint       not null,
    id                  bigint generated by default as identity,
    payment_id          bigint unique,
    room_id             bigint       not null,
    updated_at          timestamp(6),
    user_id             bigint       not null,
    status              varchar(255) not null check (status in ('RESERVED', 'CONFIRMED', 'CANCELLED')),
    primary key (id)
)

create table booking_guest
(
    booking_id bigint not null,
    guest_id   bigint not null,
    primary key (booking_id, guest_id)
)

create table guest
(
    age        integer      not null,
    created_at timestamp(6),
    id         bigint generated by default as identity,
    updated_at timestamp(6),
    user_id    bigint,
    gender     varchar(255) check (gender in ('MALE', 'FEMALE', 'OTHER')),
    name       varchar(255) not null,
    primary key (id)
)

create table hotel
(
    active       boolean      not null,
    created_at   timestamp(6),
    id           bigint generated by default as identity,
    updated_at   timestamp(6),
    address      varchar(255),
    city         varchar(255),
    email        varchar(255),
    location     varchar(255),
    name         varchar(255) not null,
    phone_number varchar(255),
    amenities    TEXT[],
    photos       TEXT[],
    primary key (id)
)

create table inventory
(
    booked_count INTEGER DEFAULT 0 not null,
    closed       boolean           not null,
    price        numeric(10, 2)    not null,
    surge_factor numeric(5, 2)     not null,
    total_count  integer           not null,
    created_at   timestamp(6),
    date_time    timestamp(6)      not null,
    hotel_id     bigint            not null,
    id           bigint generated by default as identity,
    room_id      bigint            not null,
    updated_at   timestamp(6),
    city         varchar(255)      not null,
    primary key (id),
    constraint unique_hotel_room_datetime unique (hotel_id, room_id, date_time)
)

create table payment
(
    price          numeric(10, 2) not null,
    created_at     timestamp(6),
    id             bigint generated by default as identity,
    updated_at     timestamp(6),
    status         varchar(255)   not null check (status in ('CONFIRMED', 'CANCELLED', 'PENDING')),
    transaction_id varchar(255)   not null unique,
    primary key (id)
)

create table room
(
    base_price  numeric(10, 2) not null,
    capacity    integer        not null,
    total_count integer        not null,
    created_at  timestamp(6),
    hotel_id    bigint         not null,
    id          bigint generated by default as identity,
    updated_at  timestamp(6),
    type        varchar(255)   not null,
    amenities   TEXT[],
    photos      TEXT[],
    primary key (id)
)

create table user_roles
(
    user_id bigint not null,
    roles   varchar(255) check (roles in ('GUEST', 'HOTEL_MANAGER'))
)

alter table if exists booking
    add constraint FKhacdq9bfa3r9xdimovsnonbyi
        foreign key (hotel_id)
            references hotel

alter table if exists booking
    add constraint FK70t92vvx289ayx2hq2v4hdcjl
        foreign key (payment_id)
            references payment

alter table if exists booking
    add constraint FKq83pan5xy2a6rn0qsl9bckqai
        foreign key (room_id)
            references room

alter table if exists booking
    add constraint FKn7phgawjwo673xgim9d2cvfe1
        foreign key (user_id)
            references app_user

alter table if exists booking_guest
    add constraint FKbidkmu7pdnm82qpo2r3n699yd
        foreign key (guest_id)
            references guest

alter table if exists booking_guest
    add constraint FKngrkuwlsaqjwe4mycjdvhuwtk
        foreign key (booking_id)
            references booking

alter table if exists guest
    add constraint FKdg6lwhvpl89f1yt2i40pbfiiy
        foreign key (user_id)
            references app_user

alter table if exists inventory
    add constraint FK81iasgjh573hbsoluoj670bkj
        foreign key (hotel_id)
            references hotel

alter table if exists inventory
    add constraint FKkkm00xm4as7hupix7tlg0q3of
        foreign key (room_id)
            references room

alter table if exists room
    add constraint FKdosq3ww4h9m2osim6o0lugng8
        foreign key (hotel_id)
            references hotel

alter table if exists user_roles
    add constraint FK6fql8djp64yp4q9b3qeyhr82b
        foreign key (user_id)
            references app_user